### ISSUE TITLE
Update, note about adding new maintainers

### ISSUE THREAD

**Issue by abronan** [kvtools/valkeyrie#10]
First things first, thanks to all of you who have been contributing to libkv since it started. There were plenty of quality contributions and I'm thankful for the time you have invested here.

As the original author of the library, the initial goal of of the libkv fork (which is now valkeyrie) was to keep `libkv` going. The lack of response from the upstream docker repository while also having to respect the process of the docker organisation, thus slowing down the contribution process, pushed me to focus on the fork rather than the upstream after giving up my maintainer status.

I've had some time last year to include a few changes and two new backends as well as fix a few outstanding issues for repositories such as Traefik. The problem is that I'm becoming a single point of failure and the recent lack of time to invest into valkeyrie comes at a risk for these projects that might consider rolling back to using a single Key/Value store for simplicity and stability.

I hereby propose adding maintainers to the repository (thank you @victorcoder for the kind proposal). I know that some people have been active with the libkv fork, thus I wonder if some of you are interested into maintaining this repository. Instead of say, forking it again and end up with 10 versions of libkv/valkeyrie.

I'm also willing to contribute if you need me for design decisions or some other tricky issues coming from the legacy code base.

@nmengin @emilevauge @mthenw would you be interested into getting access as a maintainer?

I've already added @victorcoder, creator of [dkron](https://github.com/victorcoder/dkron) and user of valkeyrie.

**Comment by nmengin** [comment]
Hello @abronan ,

Many thanks for the proposition, I am interested to become maintainer of valkeyrie :+1: :smiley: .

**Comment by mthenw** [comment]
Hey everyone,

I would also be interested in becoming a maintainer.  I would feel more comfortable if we could set up a separate GitHub org for that effort. What do you think? @abronan @nmengin @victorcoder

**Comment by abronan** [comment]
Yes, creating a separate org seems like a sensible choice, although we just need to make sure that this move will be the last as we went from libkv->fork->valkeyrie already so a lot of users probably couldn't follow these changes and are probably still on the upstream docker/libkv or the fork. We also need to communicate that move clearly to make sure projects update their vendor file (a move notice on this README and the fork will do I guess). But I have to keep that repository up to make sure I don't break existing projects.

*Note*: Feel free to add yourself to the Maintainers section, you should be added by now.

**Comment by mthenw** [comment]
Yeah, the chain is pretty long but looks like that would be the last move. Writing a blog post and posting on reddit/HN could help in promoting the new org/repo.

**Comment by victorcoder** [comment]
Thanks @abronan, I agree @mthenw, I think this projects deserves the place of the KV abstraction library of reference for Go, and an org could provide a neutral point to collaborate.

Also opening an issue in libkv mentioning the new repo could help in the moving.

Naming proposals?

**Comment by mthenw** [comment]
@victorcoder https://github.com/libkv? :)

**Comment by victorcoder** [comment]
@mthenw hmmm I don't know if that could be a problem with Docker inc. and I like Valkeyrie name.

valkeyrie/valkeyrie?

**Comment by mthenw** [comment]
@victorcoder `valkeyrie/valkeyrie` works for me :)

**Comment by mthenw** [comment]
But it's already taken https://github.com/valkeyrie

**Comment by victorcoder** [comment]
![](https://media3.giphy.com/media/xiAqCzbB3eZvG/giphy.gif?cid=3640f6095bc59b9964312f3951f684bd)

- `libkv/valkeyrie`
- `libkv/libkv`

**Comment by mthenw** [comment]
I'm not an expert but looks like Apache2.0 license doesn't allow that. But I might be wrong. Nevertheless, we should just pick different name.

Other options:
- `valkeyriehq/valkeyrie`
- `valkeyrielib/valkeyrie`

**Comment by victorcoder** [comment]
Agree @mthenw let's go with `valkeyrielib/valkeyrie`

**Comment by mthenw** [comment]
@victorcoder I created the organization and invited you. I will propose some plan regarding migration so we can archive @abronan repositories and start maintaining new repo.

**Comment by victorcoder** [comment]
@mthenw I joined it, thanks

**Comment by sivakrishnan-intel** [comment]
Is there any updates on new org and and a migration plan ?

**Comment by victorcoder** [comment]
## Proposed plan:

1. Transfer the repo to valkeyrielib/valkeyrie org (@abronan)
2. Place a notice in the top of the README indicating the project has moved to a new location indicating developers to update their deps.
3. Rename all references to `github.com/abronan/valkeyrie` to `github.com/valkeyrielib/valkeyrie`

What do you think @abronan @mthenw @nmengin ?

**Comment by ldez** [comment]
The repo has been migrated to a new GitHub organization :tada:
