### ISSUE TITLE
Migrate from Travis to CircleCI

### ISSUE THREAD

**Issue by abronan** [kvtools/valkeyrie#21]
Meant to do that a long time ago, using it in other projects, but I think it's time to move to CircleCI and include all the deps (etcd/consul/etc.) in a docker image. This would decrease build time and testing time dramatically at the same time of being more maintainable in the long run.

**Comment by abronan** [comment]
Travis CI builds are broken, since travis-ci.org has been deprecated and stopped in favor of travis-ci.com. Although there is no way to make it work on the new site somehow and the builds aren't starting and showing an error. Need to double down on migrating to CircleCI or Github actions.

**Comment by victorcoder** [comment]
+1 for GH Actions

**Comment by ldez** [comment]
migration to GH actions done!
