### ISSUE TITLE
Tag Release

### ISSUE THREAD

**Issue by tooolbox** [kvtools/valkeyrie#44]
Hello maintainers!

(I saw [this](https://github.com/abronan/valkeyrie/issues/10) so that may be @abronan or @victorcoder or @nmengin or @mthenw )

I just ran into duplicate protobuf registration for etcd which seems to be fixed with https://github.com/abronan/valkeyrie/commit/5ce5a684ae18cf05a4f322654365968cb33d12cf / https://github.com/abronan/valkeyrie/pull/40

Amusingly, using that commit in my go.mod does affect the panic I'm running into, but just changes it to:
```
go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200329194405-dd816f0735f8/auth/authpb/auth.pb.go:115 +0x10a
```

*sigh*

Regardless, I thought it might be a good idea to tag that commit as v0.1.1 so people pulling in this project newly get that fix, otherwise Go Modules will default to v0.1.0 and then they'll encounter the bug and have to have the determination to figure it out and eventually wind up here :)

Thanks!

EDIT: As a further note, I did just get it to work by ensuring that my project matched the version of etcd that Valkeyrie was importing.  I was using `v3.3.0-rc.0.0.20200626182840-e94dc39edcf9` versus `v0.5.0-alpha.5.0.20200329194405-dd816f0735f8`.  I'll admit that I floundered around for a while trying to determine what the correct version was to import for Go Modules--seems like that project is a bit of a disaster from that perspective.

**Comment by victorcoder** [comment]
Thanks @tooolbox, @abronan I think it's a good idea to add a new tag, WDYT?

**Comment by abronan** [comment]
I just tagged a v0.2.0 including https://github.com/abronan/valkeyrie/pull/49 which should fix all of this mess with the new client structure.
